spring:
  application:
    name: invest-security
  profiles:
    active: @spring.profiles.active@
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true


mybatis-plus:
  type-aliases-package: com.alex.spring.security.model
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    refresh-mapper: true
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
